config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'zendesk/list_tickets', to: 'zendesk#list_tickets', as: 'zendesk_list_tickets'
  get 'zendesk/show_ticket/:id', to: 'zendesk#show_ticket', as: 'zendesk_show_ticket'

  get '*path', to: redirect('/')
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def home; end
end

app/controllers/zendesk_controller.rb
# frozen_string_literal: true

class ZendeskController < ApplicationController
  include Zendesk

  before_action :initialize_zendesk_api

  def list_tickets
    @response.list_tickets(params['page'], ENV['ZENDESK_TICKETS_PER_PAGE'])
  rescue Errors::ZendeskError => e
    handle_error(e)
  end

  def show_ticket
    @response.show_ticket(params['id'])
  rescue Errors::ZendeskError => e
    handle_error(e)
  end

  private

  def initialize_zendesk_api
    @response = Zendesk::API.new
  end

  def handle_error(object)
    @alert = true
    @error = object.error
    @code = object.status
    @message = object.message
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/_contact.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <div class="well">
      <h1>Contact Details</h1>
      <div class="row">
        <div class="col-xs-6 text-right">
          Name:
        </div>
        <div class="col-xs-6 text-left">
          Alvin See
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 text-right">
          Mobile:
        </div>
        <div class="col-xs-6 text-left">
          0401639021
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 text-right">
          Email:
        </div>
        <div class="col-xs-6 text-left">
          alvin.see.hl@gmail.com
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 text-right">
          Address:
        </div>
        <div class="col-xs-6 text-left">
          3502/1 Balston Street,<br>
          Southbank 3006 Victoria,<br>
          Australia
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_link.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <div class="well">
      <h1><%= title %></h1>
      <div class="row">
        <div class="col-xs-12 text-right">
          <a href="<%= url %>" class="btn btn-primary btn-block"><%= title %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class='container'>
  <div class="content jumbotron text-center">
    <h1>Ticket Viewer</h1>
  </div>
  <%= render "contact" %>
  <%= render "link", title: "LinkedIn", url: "https://www.linkedin.com/in/han-liang-alvin-s-055715150/" %>
  <%= render "link", title: "GitLab", url: "https://gitlab.com/7ail" %>
  <%= render "link", title: "Project Source", url: "https://gitlab.com/7ail/zendesk-coding-challenge" %>
</div>

app/views/layouts/_alert.html.erb
<div class='container'>
  <div class="alert alert-danger alert-dismissible fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Error!!!</strong> <%= "#{@error}(#{@code}): #{@message}."%>
  </div>

  <a href=<%= root_path %>>
    <div class="error-content jumbotron text-center">
      <h1>HOME</h1>
    </div>
  </a>

  <a href=<%= "#{ENV['ZENDESK_URL']}/auth/v2/login/signin" %>>
    <div class="error-content jumbotron text-center">
      <%= image_tag "zendesk-wordmark.svg" %>
    </div>
  </a>
</div>

app/views/layouts/_back_button.html.erb
<% if request.env['HTTP_REFERER'] %>
  <ul class="pager">
    <li class="previous">
      <a href=<%= request.env['HTTP_REFERER'] %>>Back</a>
    </li>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="footer-copyright text-center py-3">
    <a href=<%= "#{ENV['ZENDESK_URL']}/auth/v2/login/signin" %>><%= image_tag "zendesk-wordmark.svg", size: 80 %></a>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>BluePanda</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href=<%= zendesk_list_tickets_path(page: 1) %>>List Tickets</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_pager.html.erb
<ul class="pager">
  <% if @response.body['previous_page'] %>
  <li class="previous">
    <a href=<%= zendesk_list_tickets_path(page: params['page'].to_i - 1) %>>Previous</a>
  </li>
  <% end %>
  <% if @response.body['next_page'] %>
  <li class="next">
    <a href=<%= zendesk_list_tickets_path(page: params['page'].to_i + 1) %>>Next</a>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <div id='background'></div>
  <head>
    <title>ZendeskTicketViewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alert' if @alert%>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/zendesk/list_tickets.html.erb
<% unless @alert %>
  <div class="container">
    <%= render 'layouts/pager'%>
    <% @response.body['tickets'].each do |ticket| %>
    <div class="well">
      <h1><%= ticket['subject'] %></h1>
      <div>
        <div class="<%="#{ticket['priority']}"%>">
          <h3><%= "Priority: #{(ticket['priority'] || "N/A").upcase}" %></h3>
        </div>
        <div class="<%= "#{ticket['status']}" %>">
          <h4><%= "Status: #{(ticket['status'] || "N/A").upcase}" %></h4>
        </div>
        <div class="btn-group">
          <a href=<%= "#{ENV['ZENDESK_URL']}/agent/tickets/#{ticket['id']}" %> target="_blank" class="btn btn-default" role="button">Source</a>
          <a href=<%= zendesk_show_ticket_path(ticket['id']) %> class="btn btn-primary" role="button">More Information</a>
        </div> 
      </div>
    </div>
    <% end %>
    <%= render 'layouts/pager'%>
  </div>
<% end %>

app/views/zendesk/show_ticket.html.erb
<% unless @alert %>
  <div class="container">
    <%= render "layouts/back_button" %>
    <% unless @response.body.nil? %>
      <div class="well">
        <% unless @response.body['ticket'].nil? %>
          <%= render "zendesk/show_ticket/type_priority_status", content: @response.body['ticket'] %>
          <%= render "zendesk/show_ticket/tags", content: @response.body['ticket']['tags'] %>
          <%= render "zendesk/show_ticket/subject", content: @response.body['ticket'] %>
          <%= render "zendesk/show_ticket/description", content: @response.body['ticket'] %>
          <%= render "zendesk/show_ticket/via", content: @response.body['ticket']['via'] %>
          <%= render "zendesk/show_ticket/information", content: @response.body['ticket'] %>
          <%= render "zendesk/show_ticket/source", content: @response.body['ticket'] %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/zendesk/show_ticket/_description.html.erb
<h3>Description</h3>
<div class="well">
  <%= (content['description'] || "N/A") %>
</div>

app/views/zendesk/show_ticket/_information.html.erb
<h3>Information</h3>
<div class="well">
  <%= render "zendesk/show_ticket/content_type/id", title: "ID:", content: content['id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "External ID:", content: content['external_id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Brand ID:", content: content['brand_id'] %>
  <%= render "zendesk/show_ticket/content_type/string", title: "Created At:", content: content['created_at'] %>
  <%= render "zendesk/show_ticket/content_type/string", title: "Updated At:", content: content['updated_at'] %>
  <%= render "zendesk/show_ticket/content_type/string", title: "Due At:", content: content['due_at'] %>
  <%= render "zendesk/show_ticket/content_type/string", title: "Satisfaction Rating:", content: content['satisfaction_rating'] %>
  <%= render "zendesk/show_ticket/content_type/string", title: "Recipient:", content: content['receipient'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Requester ID:", content: content['requester_id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Submitter ID:", content: content['submitter_id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Assignee ID:", content: content['assignee_id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Organization ID:", content: content['organization_id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Group ID:", content: content['group_id'] %>
  <%= render "zendesk/show_ticket/content_type/ids", title: "Collaborator IDs:", content: content['collaborator_ids'] %>
  <%= render "zendesk/show_ticket/content_type/ids", title: "Follower IDs:", content: content['follower_ids'] %>
  <%= render "zendesk/show_ticket/content_type/ids", title: "Email CC IDs:", content: content['email_cc_ids'] %>
  <%= render "zendesk/show_ticket/content_type/ids", title: "Followup IDs:", content: content['followup_ids'] %>
  <%= render "zendesk/show_ticket/content_type/ids", title: "Sharing Agreement IDs:", content: content['sharing_agreement_ids'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Forum Topic ID:", content: content['forum_topic_id'] %>
  <%= render "zendesk/show_ticket/content_type/id", title: "Problem ID:", content: content['problem_id'] %>
  <%= render "zendesk/show_ticket/content_type/fields", title: "Custom Fields:", content: content['custom_fields'] %>
  <%= render "zendesk/show_ticket/content_type/fields", title: "Fields:", content: content['fields'] %>
  <%= render "zendesk/show_ticket/content_type/boolean", title: "Has Incidents:", content: content['has_incidents'] %>
  <%= render "zendesk/show_ticket/content_type/boolean", title: "Is Public:", content: content['is_public'] %>
  <%= render "zendesk/show_ticket/content_type/boolean", title: "Allow Channelback:", content: content['allow_channelback'] %>
  <%= render "zendesk/show_ticket/content_type/boolean", title: "Allow Attachments:", content: content['allow_attachments'] %>
</div>

app/views/zendesk/show_ticket/_source.html.erb
<div class="btn-group">
  <a href=<%= ("#{ENV['ZENDESK_URL']}/agent/tickets/#{content['id']}" || "#") %> target="_blank" class="btn btn-default" role="button">Source</a>
</div> 

app/views/zendesk/show_ticket/_subject.html.erb
<h1><%= (content['subject'] || "N/A") %></h1>
<div class="well">
  <h5><%= (content['raw_subject'] || "N/A") %></h5>
</div>

app/views/zendesk/show_ticket/_tags.html.erb
<div id="tags">
  <span class="label label-default">TAGS</span>
  <% content.each do |x| %>
    <span class="label label-info"><%= x %></span>
  <% end %>
</div>

app/views/zendesk/show_ticket/_type_priority_status.html.erb
<div class="btn-group">
  <button type="button" class="btn disabled">Type</button>
  <button type="button" class="btn btn-primary disabled"><%= (content['type'] || "N/A") %></button>
</div>

<div class="btn-group">
  <button type="button" class="btn disabled">Priority</button>
  <button type="button" class="<%= 'btn disabled ' + "btn-#{content['priority']}"%>"><%= (content['priority'] || "N/A") %></button>
</div>

<div class="btn-group">
  <button type="button" class="btn disabled">Status</button>
  <button type="button" class="<%= 'btn disabled ' + "btn-#{content['status']}"%>"><%= (content['status'] || "N/A") %></button>
</div>

app/views/zendesk/show_ticket/_via.html.erb
<% unless content.nil? %>
  <h3>Via</h3>
  <div class="well">
    <%= render "zendesk/show_ticket/content_type/string", title: "Channel:", content: content['channel'] %>   
    <div class="row">
      <div class="col-xs-6">
        <p>
          Source
        </p>
      </div>
      <div class="col-xs-6">
        <% unless content['source'].nil? %>
          <div class="well">
            <%= render "zendesk/show_ticket/content_type/string", title: "From:", content: content['source']['from'] %>
            <%= render "zendesk/show_ticket/content_type/string", title: "To:", content: content['source']['to'] %>
            <%= render "zendesk/show_ticket/content_type/string", title: "Rel:", content: content['source']['rel'] %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/zendesk/show_ticket/content_type/_boolean.html.erb
<div class="row">
  <div class="col-xs-6">
    <p>
      <%= title %>
    </p>
  </div>
  <div class="col-xs-6">
    <p>
      <% if content %>
        <span class="glyphicon glyphicon-ok" style="color:green"></span>
      <% else %>
        <span class="glyphicon glyphicon-remove" style="color:red"></span>
      <% end %>
    </p>
  </div>
</div>

app/views/zendesk/show_ticket/content_type/_fields.html.erb
<div class="row">
  <div class="col-xs-6">
    <p>
      <%= title %>
    </p>
  </div>
  <div class="col-xs-6">
    <% if content.empty? %>
      <span class="label label-default">N/A</span>
    <% else %>
      <% content.each do |x| %>
        <span class="label label-default"><%= x['value'] %></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/zendesk/show_ticket/content_type/_id.html.erb
<div class="row">
  <div class="col-xs-6">
    <p>
      <%= title %>
    </p>
  </div>
  <div class="col-xs-6">
    <p>
      <span class="label label-default"><%= (content || "N/A") %></span>
    </p>
  </div>
</div>

app/views/zendesk/show_ticket/content_type/_ids.html.erb
<div class="row">
  <div class="col-xs-6">
    <p>
      <%= title %>
    </p>
  </div>
  <div class="col-xs-6">
    <% if content.empty? %>
      <span class="label label-default">N/A</span>
    <% else %>
      <% content.each do |x| %>
        <span class="label label-default"><%= x %></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/zendesk/show_ticket/content_type/_string.html.erb
<div class="row">
  <div class="col-xs-6">
    <p>
      <%= title %>
    </p>
  </div>
  <div class="col-xs-6">
    <p>
      <%= (content || "N/A") %>
    </p>
  </div>
</div>